front:
    resource: "@FrontBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_user_persona:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user/persona
app_user_role:
    resource: "@AppBundle/Resources/config/routing/role.yml"
    prefix:   /user/role
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
logout:
    path: /logout
