# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    slugger.class: AppBundle\Utils\Slugger
#    parameter_name: value

services:
    app.slugger:
        class: "%slugger.class%"
        #tags:
        #    -  { name: security.secure_service }
       # arguments: ["@security.authorization_checker"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
