user_persona:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }

user_persona_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }

user_persona_new:
    path:     /new
    defaults: { _controller: "AppBundle:User:new" }

user_persona_create:
    path:     /create
    defaults: { _controller: "AppBundle:User:create" }
    methods:  POST

user_persona_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }

user_persona_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:User:update" }
    methods:  [POST, PUT]

user_persona_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  [POST, DELETE]
